# See   https://kubernetes.io/docs/api-reference/v1.8/#clusterrole-v1beta1-rbac
#       https://kubernetes.io/docs/api-reference/v1.8/#policyrule-v1beta1-rbac
# Cluster role which allows
#   Listing all namespaces
#   Getting and updating a specific secret in each namespace - Will contain the ECR image pull secret
#   Can't use resource names to limit the creation of secrets (Would never be able to create !), see https://kubernetes.io/docs/admin/authorization/rbac/#referring-to-resources
#	"Because resource names are not present in the URL for create, list, watch, and delete collection API requests, those verbs would not be allowed by a rule with resourceNames set"


apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: eatr
rules:
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - secrets
  verbs: ["create"]
- apiGroups: [""]
  resources:
  - secrets
  resourceNames: ["*.dkr.ecr.*.amazonaws.com"]  # PENDING: Can't use this, will need explicit names, so will probably need to make this dynamic, may also need list now
  verbs: ["get", "update"]
