apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: eatr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eatr
subjects:
- kind: ServiceAccount
  name: eatr
  namespace: {{NAMESPACE}}
