apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: eatr
  name: eatr
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: eatr
    spec:
      containers:
      - image: {{EATR_IMAGE}}
        imagePullPolicy: Always
        name: eatr
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: .25
            memory: 100Mi
          requests:
            cpu: .10
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: "false"
          privileged: "false"
          readOnlyRootFilesystem: "true"
          runAsNonRoot: "false"
          runAsUser: 1000
      serviceAccountName: eatr